### PR TITLE
(Fixed typos) Add yoru. to Samsung and Featured Themes, add Transparent Lockscreen to Samsung Themes, Update the StatusBar Icons for Samsung listings

### PR DESCRIPTION
**Pull request by ohayoubaka**

### CODE REVIEW

**Comment by nathanchance** [comment]
The showcase breaks when there are titles of the form `title` and `title donate` (it can't parse them correctly I guess), could you update the free themes to be `title free` or however you want it to be called?

**Comment by ohayoubaka** [comment]
Yeah there were some typos, I fixed them.

**Comment by nathanchance** [comment]
Thanks! See the discussion on #49 for what I am talking about though.

**Comment by ohayoubaka** [comment]
Ty for the heads up, added a commit to fix that.

**Comment by nathanchance** [comment]
Manually merged via 274319e376d5df0dc01c63c9029411069ebff0fb, tidied up some indentation. Thank you for doing this!

**Pull request closed without merging**
