### PR TITLE
Database: updated Vivid banners

### PR DESCRIPTION
**Pull request by ami87**
The link to the free theme "Vivid Navbars Quicksettings", in the showcase, is not working. I checked in the substratum_tab_systemui_tweaks.xml and it is already correct: "https://play.google.com/store/apps/details?id=com.ami.vivid"
Can you check this guys?

### CODE REVIEW

**Comment by nathanchance** [comment]
What do you mean by not working?

**Comment by ami87** [comment]
I got the activity_missing_toast:
"There were no apps found that could handle this request, sorry!"

**Comment by nathanchance** [comment]
I see that's going on and trying something now

**Comment by ami87** [comment]
Ok, everything is fine now, thank you Nathan!

**Comment by nathanchance** [comment]
Awesome!

Unfortunately, it seems that themes cannot be in the format `<theme_name>` and `<theme_name> Pro` without the showcase having a fit. So from now on, we'll do `<theme_name> Free` and <theme_name> Pro`.

Reference commit: https://github.com/substratum/database/commit/257c2f0e80be428a8a4478fefbf1d2577ac9f5fa

**Comment by ami87** [comment]
Oh ok, got it, thanks again ;)

**Pull request merged**
