### PR TITLE
Add Curve

### PR DESCRIPTION
**Pull request by allstargaurav**

### CODE REVIEW

**Comment by nathanchance** [comment]
You need to add the `curve.png` file to the images folder as well.

**Comment by allstargaurav** [comment]
It says push access required for this repo

**Comment by nathanchance** [comment]
It looks like you're doing everything via GitHub's web interface, you really should be using the command line. Just upload the `curve.png` image somewhere that I can download and I'll handle it.

**Comment by nathanchance** [comment]
Manually merged via a465c589da39cdd6c095ac2deee0701633455ac0, thanks!

**Pull request closed without merging**
